language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install: "pip install -r requirements.txt"

before_script:
  - apt-get -y install texlive-latex-base
  - apt-get -y install texlive-pstricks

script:
  - /usr/bin/latex -interaction=batchmode barcodes.tex
  - /usr/bin/dvips barcodes.dvi
  - /usr/bin/ps2pdf barcodes.ps
