sudo: required
dist: trusty
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install: "pip install -r requirements.txt"

before_script:
  - sudo apt-get -y install texlive-latex-base
  - sudo apt-get -y install texlive-pstricks
#  - sudo apt-get -y install texlive-xetex

script:
  - python3 -m compileall *.py # check syntax errors for python
  - latex -interaction=nonstopmode barcodes.tex
  - dvips barcodes.dvi
  - ps2pdf barcodes.ps
#  - xelatex -interaction=batchmode barcodes.tex
